docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:test" --target test .
    - docker build --pull -t "$CI_REGISTRY_IMAGE:dev" --target dev .
    - docker build --pull -t "$CI_REGISTRY_IMAGE:production" -t "$CI_REGISTRY_IMAGE:latest" --target production .
    - docker push "$CI_REGISTRY_IMAGE:test"
    - docker push "$CI_REGISTRY_IMAGE:dev"
    - docker push "$CI_REGISTRY_IMAGE:production" 
    - docker push "$CI_REGISTRY_IMAGE:latest"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
